spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RentalCarDB?createDatabaseIfNotExist=true
    username: myuser
    password: secret123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database: mysql
    database-platform: MYSQL

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: RentalCarDB


  devtools:
    livereload:
      enabled: true
    add-properties: true

  output:
    ansi:
      enabled: ALWAYS

server:
  error:
    #this helps to avoid the long trace message.
    include-stacktrace: never